const orders = [
    {
      restaurant: "610f6a2ebaa34e0015f00a1a", // ObjectId of a Restaurant
      user: "610f6a2ebaa34e0015f00b1b", // ObjectId of a User
      deliveryDetails: {
        email: "user1@example.com",
        name: "John Doe",
        longtitude: -73.935242,
        latitude: 40.73061,
      },
      cartItems: [
        { menuItemId: "123abc", quantity: 2, name: "Pizza" },
        { menuItemId: "456def", quantity: 1, name: "Salad" },
      ],
      totalAmount: 25.5,
      status: "placed",
      createdAt: new Date("2023-01-15"),
    },
    {
      restaurant: "610f6a2ebaa34e0015f00a1b",
      user: "610f6a2ebaa34e0015f00b2b",
      deliveryDetails: {
        email: "user2@example.com",
        name: "Jane Smith",
        longtitude: -74.006,
        latitude: 40.7128,
      },
      cartItems: [
        { menuItemId: "789ghi", quantity: 1, name: "Burger" },
        { menuItemId: "abc123", quantity: 3, name: "French Fries" },
      ],
      totalAmount: 18.75,
      status: "paid",
      createdAt: new Date("2023-02-20"),
    },
    {
      restaurant: "610f6a2ebaa34e0015f00a1c",
      user: "610f6a2ebaa34e0015f00b3b",
      deliveryDetails: {
        email: "user3@example.com",
        name: "Emily Johnson",
        longtitude: -73.9912,
        latitude: 40.7397,
      },
      cartItems: [
        { menuItemId: "def456", quantity: 1, name: "Sushi Roll" },
        { menuItemId: "ghi789", quantity: 2, name: "Miso Soup" },
      ],
      totalAmount: 32.0,
      status: "inProgress",
      createdAt: new Date("2023-03-10"),
    },
    {
      restaurant: "610f6a2ebaa34e0015f00a1d",
      user: "610f6a2ebaa34e0015f00b4b",
      deliveryDetails: {
        email: "user4@example.com",
        name: "Michael Brown",
        longtitude: -73.9776,
        latitude: 40.7831,
      },
      cartItems: [
        { menuItemId: "jkl012", quantity: 2, name: "Steak" },
        { menuItemId: "mno345", quantity: 1, name: "Potato Wedges" },
      ],
      totalAmount: 45.25,
      status: "outForDelivery",
      createdAt: new Date("2023-04-05"),
    },
    {
      restaurant: "610f6a2ebaa34e0015f00a1e",
      user: "610f6a2ebaa34e0015f00b5b",
      deliveryDetails: {
        email: "user5@example.com",
        name: "Sophia Lee",
        longtitude: -73.9866,
        latitude: 40.7306,
      },
      cartItems: [
        { menuItemId: "pqr678", quantity: 1, name: "Chicken Wrap" },
        { menuItemId: "stu901", quantity: 2, name: "Caesar Salad" },
      ],
      totalAmount: 22.0,
      status: "delivered",
      createdAt: new Date("2023-05-15"),
    },
    {
        restaurant: "610f6a2ebaa34e0015f00a1f",
        user: "610f6a2ebaa34e0015f00b6b",
        deliveryDetails: {
          email: "user6@example.com",
          name: "David Wilson",
          longtitude: -73.945,
          latitude: 40.670,
        },
        cartItems: [
          { menuItemId: "vwx123", quantity: 3, name: "Pasta" },
          { menuItemId: "yz789", quantity: 1, name: "Garlic Bread" },
        ],
        totalAmount: 28.50,
        status: "placed",
        createdAt: new Date("2023-06-01"),
    },
    {
    restaurant: "610f6a2ebaa34e0015f00a20",
    user: "610f6a2ebaa34e0015f00b7b",
    deliveryDetails: {
        email: "user7@example.com",
        name: "Olivia Martinez",
        longtitude: -74.010,
        latitude: 40.750,
    },
    cartItems: [
        { menuItemId: "abc456", quantity: 2, name: "Tacos" },
        { menuItemId: "def012", quantity: 2, name: "Guacamole" },
    ],
    totalAmount: 24.75,
    status: "paid",
    createdAt: new Date("2023-07-10"),
    },
    {
    restaurant: "610f6a2ebaa34e0015f00a21",
    user: "610f6a2ebaa34e0015f00b8b",
    deliveryDetails: {
        email: "user8@example.com",
        name: "Sophie Brown",
        longtitude: -73.990,
        latitude: 40.740,
    },
    cartItems: [
        { menuItemId: "ghi345", quantity: 1, name: "Sushi Combo" },
        { menuItemId: "jkl678", quantity: 3, name: "Miso Soup" },
    ],
    totalAmount: 35.80,
    status: "inProgress",
    createdAt: new Date("2023-08-15"),
    },
    {
    restaurant: "610f6a2ebaa34e0015f00a22",
    user: "610f6a2ebaa34e0015f00b9b",
    deliveryDetails: {
        email: "user9@example.com",
        name: "Daniel Garcia",
        longtitude: -73.980,
        latitude: 40.760,
    },
    cartItems: [
        { menuItemId: "mno456", quantity: 2, name: "Ribeye Steak" },
        { menuItemId: "pqr789", quantity: 1, name: "Mashed Potatoes" },
    ],
    totalAmount: 52.25,
    status: "outForDelivery",
    createdAt: new Date("2023-09-20"),
    },
    {
    restaurant: "610f6a2ebaa34e0015f00a23",
    user: "610f6a2ebaa34e0015f00bab",
    deliveryDetails: {
        email: "user10@example.com",
        name: "Emma Johnson",
        longtitude: -73.955,
        latitude: 40.780,
    },
    cartItems: [
        { menuItemId: "stu345", quantity: 1, name: "Lamb Burger" },
        { menuItemId: "vwx678", quantity: 2, name: "Truffle Fries" },
    ],
    totalAmount: 29.50,
    status: "delivered",
    createdAt: new Date("2023-10-05"),
    },
    {
        restaurant: "610f6a2ebaa34e0015f00a24",
        user: "610f6a2ebaa34e0015f00bbb",
        deliveryDetails: {
          email: "user11@example.com",
          name: "Ethan Miller",
          longtitude: -73.970,
          latitude: 40.790,
        },
        cartItems: [
          { menuItemId: "yz012", quantity: 2, name: "Chicken Parmesan" },
          { menuItemId: "abc789", quantity: 1, name: "Caesar Salad" },
        ],
        totalAmount: 34.25,
        status: "delivered",
        createdAt: new Date("2023-11-15"),
      },
      {
        restaurant: "610f6a2ebaa34e0015f00a25",
        user: "610f6a2ebaa34e0015f00bcc",
        deliveryDetails: {
          email: "user12@example.com",
          name: "Ava Robinson",
          longtitude: -73.980,
          latitude: 40.750,
        },
        cartItems: [
          { menuItemId: "def901", quantity: 1, name: "Pho Noodle Soup" },
          { menuItemId: "ghi234", quantity: 2, name: "Spring Rolls" },
        ],
        totalAmount: 28.50,
        status: "paid",
        createdAt: new Date("2023-12-01"),
      },
      {
        restaurant: "610f6a2ebaa34e0015f00a26",
        user: "610f6a2ebaa34e0015f00cdd",
        deliveryDetails: {
          email: "user13@example.com",
          name: "Logan Hall",
          longtitude: -73.990,
          latitude: 40.740,
        },
        cartItems: [
          { menuItemId: "jkl567", quantity: 3, name: "BBQ Ribs" },
          { menuItemId: "mno890", quantity: 1, name: "Cornbread" },
        ],
        totalAmount: 42.75,
        status: "inProgress",
        createdAt: new Date("2024-01-10"),
      },
      {
        restaurant: "610f6a2ebaa34e0015f00a27",
        user: "610f6a2ebaa34e0015f00dee",
        deliveryDetails: {
          email: "user14@example.com",
          name: "Mia Martinez",
          longtitude: -73.960,
          latitude: 40.770,
        },
        cartItems: [
          { menuItemId: "pqr123", quantity: 2, name: "Vegetarian Pizza" },
          { menuItemId: "stu456", quantity: 1, name: "Garlic Knots" },
        ],
        totalAmount: 30.00,
        status: "outForDelivery",
        createdAt: new Date("2024-02-20"),
      },
      {
        restaurant: "610f6a2ebaa34e0015f00a28",
        user: "610f6a2ebaa34e0015f00eff",
        deliveryDetails: {
          email: "user15@example.com",
          name: "Noah Brown",
          longtitude: -73.970,
          latitude: 40.780,
        },
        cartItems: [
          { menuItemId: "vwx345", quantity: 1, name: "Shrimp Scampi" },
          { menuItemId: "yz678", quantity: 2, name: "Caprese Salad" },
        ],
        totalAmount: 36.50,
        status: "placed",
        createdAt: new Date("2024-03-05"),
      },
      {
        restaurant: "610f6a2ebaa34e0015f00a29",
        user: "610f6a2ebaa34e0015f00fff",
        deliveryDetails: {
          email: "user16@example.com",
          name: "Isabella Lee",
          longtitude: -73.980,
          latitude: 40.760,
        },
        cartItems: [
          { menuItemId: "abc345", quantity: 2, name: "Pad Thai" },
          { menuItemId: "def678", quantity: 1, name: "Tom Yum Soup" },
        ],
        totalAmount: 26.75,
        status: "paid",
        createdAt: new Date("2024-04-10"),
      },
      {
        restaurant: "610f6a2ebaa34e0015f00a2a",
        user: "610f6a2ebaa34e0015f00eee",
        deliveryDetails: {
          email: "user17@example.com",
          name: "James Taylor",
          longtitude: -73.990,
          latitude: 40.730,
        },
        cartItems: [
          { menuItemId: "ghi567", quantity: 1, name: "Cheeseburger" },
          { menuItemId: "jkl890", quantity: 2, name: "Onion Rings" },
        ],
        totalAmount: 18.50,
        status: "delivered",
        createdAt: new Date("2024-05-01"),
      },
      {
        restaurant: "610f6a2ebaa34e0015f00a2b",
        user: "610f6a2ebaa34e0015f00ddd",
        deliveryDetails: {
          email: "user18@example.com",
          name: "Elijah Hernandez",
          longtitude: -73.970,
          latitude: 40.780,
        },
        cartItems: [
          { menuItemId: "mno012", quantity: 2, name: "Chicken Wings" },
          { menuItemId: "pqr345", quantity: 1, name: "Buffalo Dip" },
        ],
        totalAmount: 22.25,
        status: "inProgress",
        createdAt: new Date("2024-06-15"),
      },
      {
        restaurant: "610f6a2ebaa34e0015f00a2c",
        user: "610f6a2ebaa34e0015f00ccc",
        deliveryDetails: {
          email: "user19@example.com",
          name: "Aiden Moore",
          longtitude: -73.960,
          latitude: 40.770,
        },
        cartItems: [
          { menuItemId: "stu901", quantity: 1, name: "Margherita Pizza" },
          { menuItemId: "vwx234", quantity: 2, name: "Garlic Breadsticks" },
        ],
        totalAmount: 19.50,
        status: "outForDelivery",
        createdAt: new Date("2024-07-01"),
      },
      {
        restaurant: "610f6a2ebaa34e0015f00a2d",
        user: "610f6a2ebaa34e0015f00bbb",
        deliveryDetails: {
          email: "user20@example.com",
          name: "Charlotte Garcia",
          longtitude: -73.950,
          latitude: 40.760,
        },
        cartItems: [
          { menuItemId: "yz012", quantity: 3, name: "Spaghetti Carbonara" },
          { menuItemId: "abc456", quantity: 1, name: "Caesar Salad" },
        ],
        totalAmount: 32.75,
        status: "placed",
        createdAt: new Date("2024-08-10"),
      },
];
const bookings = [
    {
      price: 1500,
      address: "123 Main St",
      city: "New York",
      bedroom: 2,
      bathroom: 1,
      userId: "610f6a2ebaa34e0015f00aaa",
      createdAt: new Date("2023-01-15"),
    },
    {
      price: 2000,
      address: "456 Elm St",
      city: "Los Angeles",
      bedroom: 3,
      bathroom: 2,
      userId: "610f6a2ebaa34e0015f00bbb",
      createdAt: new Date("2023-02-20"),
    },
    {
      price: 1800,
      address: "789 Oak St",
      city: "Chicago",
      bedroom: 2,
      bathroom: 2,
      userId: "610f6a2ebaa34e0015f00ccc",
      createdAt: new Date("2023-03-10"),
    },
    {
      price: 2200,
      address: "101 Pine St",
      city: "San Francisco",
      bedroom: 3,
      bathroom: 2,
      userId: "610f6a2ebaa34e0015f00ddd",
      createdAt: new Date("2023-04-05"),
    },
    {
      price: 1600,
      address: "222 Cedar St",
      city: "Miami",
      bedroom: 2,
      bathroom: 1,
      userId: "610f6a2ebaa34e0015f00eee",
      createdAt: new Date("2023-05-15"),
    },
    {
      price: 1900,
      address: "333 Maple St",
      city: "Seattle",
      bedroom: 3,
      bathroom: 2,
      userId: "610f6a2ebaa34e0015f00fff",
      createdAt: new Date("2023-06-20"),
    },
    {
      price: 1700,
      address: "444 Walnut St",
      city: "Boston",
      bedroom: 2,
      bathroom: 1,
      userId: "610f6a2ebaa34e0015f00aaa",
      createdAt: new Date("2023-07-10"),
    },
    {
      price: 2100,
      address: "555 Birch St",
      city: "Denver",
      bedroom: 3,
      bathroom: 2,
      userId: "610f6a2ebaa34e0015f00bbb",
      createdAt: new Date("2023-08-05"),
    },
    {
      price: 1750,
      address: "666 Pine St",
      city: "Austin",
      bedroom: 2,
      bathroom: 1,
      userId: "610f6a2ebaa34e0015f00ccc",
      createdAt: new Date("2023-09-15"),
    },
    {
      price: 2300,
      address: "777 Oak St",
      city: "Portland",
      bedroom: 3,
      bathroom: 2,
      userId: "610f6a2ebaa34e0015f00ddd",
      createdAt: new Date("2023-10-10"),
    },
    {
      price: 1800,
      address: "888 Elm St",
      city: "San Diego",
      bedroom: 2,
      bathroom: 1,
      userId: "610f6a2ebaa34e0015f00eee",
      createdAt: new Date("2023-11-20"),
    },
    {
      price: 1950,
      address: "999 Maple St",
      city: "Dallas",
      bedroom: 3,
      bathroom: 2,
      userId: "610f6a2ebaa34e0015f00fff",
      createdAt: new Date("2023-12-05"),
    },
    {
      price: 1850,
      address: "111 Pine St",
      city: "Atlanta",
      bedroom: 2,
      bathroom: 1,
      userId: "610f6a2ebaa34e0015f00aaa",
      createdAt: new Date("2024-01-15"),
    },
    {
      price: 2150,
      address: "222 Cedar St",
      city: "Houston",
      bedroom: 3,
      bathroom: 2,
      userId: "610f6a2ebaa34e0015f00bbb",
      createdAt: new Date("2024-02-20"),
    },
    {
      price: 1925,
      address: "333 Oak St",
      city: "Phoenix",
      bedroom: 2,
      bathroom: 2,
      userId: "610f6a2ebaa34e0015f00ccc",
      createdAt: new Date("2024-03-10"),
    },
    {
      price: 2250,
      address: "444 Maple St",
      city: "Las Vegas",
      bedroom: 3,
      bathroom: 2,
      userId: "610f6a2ebaa34e0015f00ddd",
      createdAt: new Date("2024-04-05"),
    },
    {
      price: 1650,
      address: "555 Elm St",
      city: "Philadelphia",
      bedroom: 2,
      bathroom: 1,
      userId: "610f6a2ebaa34e0015f00eee",
      createdAt: new Date("2024-05-15"),
    },
    {
      price: 1990,
      address: "666 Cedar St",
      city: "Charlotte",
      bedroom: 3,
      bathroom: 2,
      userId: "610f6a2ebaa34e0015f00fff",
      createdAt: new Date("2024-06-20"),
    },
    {
      price: 1725,
      address: "777 Pine St",
      city: "Nashville",
      bedroom: 2,
      bathroom: 1,
      userId: "610f6a2ebaa34e0015f00aaa",
      createdAt: new Date("2024-07-10"),
    },
    {
      price: 2350,
      address: "888 Oak St",
      city: "Orlando",
      bedroom: 3,
      bathroom: 2,
      userId: "610f6a2ebaa34e0015f00bbb",
      createdAt: new Date("2024-08-05"),
    },
  ];
  
  
  const countryMappings = {
    'United States': 'USA',
    'Canada': 'CAN',
    'United Kingdom': 'GBR',
    'Australia': 'AUS',
    'Germany': 'DEU',
    'Afghanistan': 'AFG',
    'Albania': 'ALB',
    'Algeria': 'DZA',
    'Andorra': 'AND',
    'Angola': 'AGO',
    'Antigua and Barbuda': 'ATG',
    'Argentina': 'ARG',
    'Armenia': 'ARM',
    'Austria': 'AUT',
    'Azerbaijan': 'AZE',
    'Bahamas': 'BHS',
    'Bahrain': 'BHR',
    'Bangladesh': 'BGD',
    'Barbados': 'BRB',
    'Belarus': 'BLR',
    'Belgium': 'BEL',
    'Belize': 'BLZ',
    'Benin': 'BEN',
    'Bhutan': 'BTN',
    'Bolivia': 'BOL',
    'Bosnia and Herzegovina': 'BIH',
    'Botswana': 'BWA',
    'Brazil': 'BRA',
    'Brunei': 'BRN',
    'Bulgaria': 'BGR',
    'Burkina Faso': 'BFA',
    'Burundi': 'BDI',
    'Cabo Verde': 'CPV',
    'Cambodia': 'KHM',
    'Cameroon': 'CMR',
    'Central African Republic': 'CAF',
    'Chad': 'TCD',
    'Chile': 'CHL',
    'China': 'CHN',
    'Colombia': 'COL',
    'Comoros': 'COM',
    'Congo': 'COG',
    'Costa Rica': 'CRI',
    'Croatia': 'HRV',
    'Cuba': 'CUB',
    'Cyprus': 'CYP',
    'Czechia': 'CZE',
    'Denmark': 'DNK',
    'Djibouti': 'DJI',
    'Dominica': 'DMA',
    'Dominican Republic': 'DOM',
    'Ecuador': 'ECU',
    'Egypt': 'EGY',
    'El Salvador': 'SLV',
    'Equatorial Guinea': 'GNQ',
    'Eritrea': 'ERI',
    'Estonia': 'EST',
    'Eswatini': 'SWZ',
    'Ethiopia': 'ETH',
    'Fiji': 'FJI',
    'Finland': 'FIN',
    'France': 'FRA',
    'Gabon': 'GAB',
    'Gambia': 'GMB',
    'Georgia': 'GEO',
    'Ghana': 'GHA',
    'Greece': 'GRC',
    'Grenada': 'GRD',
    'Guatemala': 'GTM',
    'Guinea': 'GIN',
    'Guinea-Bissau': 'GNB',
    'Guyana': 'GUY',
    'Haiti': 'HTI',
    'Honduras': 'HND',
    'Hungary': 'HUN',
    'Iceland': 'ISL',
    'India': 'IND',
    'Indonesia': 'IDN',
    'Iran': 'IRN',
    'Iraq': 'IRQ',
    'Ireland': 'IRL',
    'Israel': 'ISR',
    'Italy': 'ITA',
    'Jamaica': 'JAM',
    'Japan': 'JPN',
    'Jordan': 'JOR',
    'Kazakhstan': 'KAZ',
    'Kenya': 'KEN',
    'Kiribati': 'KIR',
    'Korea (North)': 'PRK',
    'Korea (South)': 'KOR',
    'Kosovo': 'XKX',
    'Kuwait': 'KWT',
    'Kyrgyzstan': 'KGZ',
    'Laos': 'LAO',
    'Latvia': 'LVA',
    'Lebanon': 'LBN',
    'Lesotho': 'LSO',
    'Liberia': 'LBR',
    'Libya': 'LBY',
    'Liechtenstein': 'LIE',
    'Lithuania': 'LTU',
    'Luxembourg': 'LUX',
    'Madagascar': 'MDG',
    'Malawi': 'MWI',
    'Malaysia': 'MYS',
    'Maldives': 'MDV',
    'Mali': 'MLI',
    'Malta': 'MLT',
    'Marshall Islands': 'MHL',
    'Mauritania': 'MRT',
    'Mauritius': 'MUS',
    'Mexico': 'MEX',
    'Micronesia': 'FSM',
    'Moldova': 'MDA',
    'Monaco': 'MCO',
    'Mongolia': 'MNG',
    'Montenegro': 'MNE',
    'Morocco': 'MAR',
    'Mozambique': 'MOZ',
    'Myanmar (Burma)': 'MMR',
    'Namibia': 'NAM',
    'Nauru': 'NRU',
    'Nepal': 'NPL',
    'Netherlands': 'NLD',
    'New Zealand': 'NZL',
    'Nicaragua': 'NIC',
    'Niger': 'NER',
    'Nigeria': 'NGA',
    'North Macedonia': 'MKD',
    'Norway': 'NOR',
    'Oman': 'OMN',
    'Pakistan': 'PAK',
    'Palau': 'PLW',
    'Palestine': 'PSE',
    'Panama': 'PAN',
    'Papua New Guinea': 'PNG',
    'Paraguay': 'PRY',
    'Peru': 'PER',
    'Philippines': 'PHL',
    'Poland': 'POL',
    'Portugal': 'PRT',
    'Qatar': 'QAT',
    'Romania': 'ROU',
    'Russia': 'RUS',
    'Rwanda': 'RWA',
    'Saint Kitts and Nevis': 'KNA',
    'Saint Lucia': 'LCA',
    'Saint Vincent and the Grenadines': 'VCT',
    'Samoa': 'WSM',
    'San Marino': 'SMR',
    'Sao Tome and Principe': 'STP',
    'Saudi Arabia': 'SAU',
    'Senegal': 'SEN',
    'Serbia': 'SRB',
    'Seychelles': 'SYC',
    'Sierra Leone': 'SLE',
    'Singapore': 'SGP',
    'Slovakia': 'SVK',
    'Slovenia': 'SVN',
    'Solomon Islands': 'SLB',
    'Somalia': 'SOM',
    'South Africa': 'ZAF',
    'South Sudan': 'SSD',
    'Spain': 'ESP',
    'Sri Lanka': 'LKA',
    'Sudan': 'SDN',
    'Suriname': 'SUR',
    'Sweden': 'SWE',
    'Switzerland': 'CHE',
    'Syria': 'SYR',
    'Taiwan': 'TWN',
    'Tajikistan': 'TJK',
    'Tanzania': 'TZA',
    'Thailand': 'THA',
    'Timor-Leste': 'TLS',
    'Togo': 'TGO',
    'Tonga': 'TON',
    'Trinidad and Tobago': 'TTO',
    'Tunisia': 'TUN',
    'Turkey': 'TUR',
    'Turkmenistan': 'TKM',
    'Tuvalu': 'TUV',
    'Uganda': 'UGA',
    'Ukraine': 'UKR',
    'United Arab Emirates': 'ARE',
    'Uruguay': 'URY',
    'Uzbekistan': 'UZB',
    'Vanuatu': 'VUT',
    'Vatican City': 'VAT',
    'Venezuela': 'VEN',
    'Vietnam': 'VNM',
    'Yemen': 'YEM',
    'Zambia': 'ZMB',
    'Zimbabwe': 'ZWE'
    // Add more country mappings as needed
  };
  
  const users = [
    {
      imageId: '6151ee38c5b92b601f3d5626',
      name: 'Matthew Cook',
      email: 'matthew.cook@example.com',
      password: 'password40',
      country: 'Bolivia',
      hotels: [],
      phone: 5554443333,
      userType: 'ADMIN',
      longitude: -63.5887,
      latitude: -16.2902,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5627',
      name: 'Liam Ward',
      email: 'liam.ward@example.com',
      password: 'password41',
      country: 'Bosnia and Herzegovina',
      hotels: [],
      phone: 4445556666,
      userType: 'USER',
      longitude: 17.6791,
      latitude: 43.9159,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5628',
      name: 'Charlotte Rivera',
      email: 'charlotte.rivera@example.com',
      password: 'password42',
      country: 'Botswana',
      hotels: [],
      phone: 3332221111,
      userType: 'ADMIN',
      longitude: 24.6849,
      latitude: -22.3285,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5629',
      name: 'William Ward',
      email: 'william.ward@example.com',
      password: 'password43',
      country: 'Brazil',
      hotels: [],
      phone: 8889990000,
      userType: 'USER',
      longitude: -51.9253,
      latitude: -14.235,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5630',
      name: 'Amelia Roberts',
      email: 'amelia.roberts@example.com',
      password: 'password44',
      country: 'Brunei',
      hotels: [],
      phone: 7776665555,
      userType: 'ADMIN',
      longitude: 114.7277,
      latitude: 4.5353,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5631',
      name: 'Daniel Foster',
      email: 'daniel.foster@example.com',
      password: 'password45',
      country: 'Bulgaria',
      hotels: [],
      phone: 6665554444,
      userType: 'USER',
      longitude: 25.4858,
      latitude: 42.7339,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5632',
      name: 'Olivia Garcia',
      email: 'olivia.garcia@example.com',
      password: 'password46',
      country: 'Burkina Faso',
      hotels: [],
      phone: 5556667777,
      userType: 'ADMIN',
      longitude: -1.5616,
      latitude: 12.2383,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5633',
      name: 'Ethan Young',
      email: 'ethan.young@example.com',
      password: 'password47',
      country: 'Burundi',
      hotels: [],
      phone: 4443332222,
      userType: 'USER',
      longitude: 29.9189,
      latitude: -3.3731,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5634',
      name: 'Ava Carter',
      email: 'ava.carter@example.com',
      password: 'password48',
      country: 'Cabo Verde',
      hotels: [],
      phone: 3334445555,
      userType: 'ADMIN',
      longitude: -23.0418,
      latitude: 16.5388,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5635',
      name: 'Alexander Flores',
      email: 'alexander.flores@example.com',
      password: 'password49',
      country: 'Cambodia',
      hotels: [],
      phone: 2223334444,
      userType: 'USER',
      longitude: 104.99096,
      latitude: 12.5657,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5636',
      name: 'Madison King',
      email: 'madison.king@example.com',
      password: 'password50',
      country: 'Cameroon',
      hotels: [],
      phone: 1112223333,
      userType: 'ADMIN',
      longitude: 11.5174,
      latitude: 3.848,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5637',
      name: 'Lucas Wright',
      email: 'lucas.wright@example.com',
      password: 'password51',
      country: 'Canada',
      hotels: [],
      phone: 9998887777,
      userType: 'USER',
      longitude: -79.3832,
      latitude: 43.6532,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5638',
      name: 'Isabella Lee',
      email: 'isabella.lee@example.com',
      password: 'password52',
      country: 'Central African Republic',
      hotels: [],
      phone: 8887776666,
      userType: 'ADMIN',
      longitude: 20.9394,
      latitude: 6.6111,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5639',
      name: 'Jackson Hill',
      email: 'jackson.hill@example.com',
      password: 'password53',
      country: 'Chad',
      hotels: [],
      phone: 7776665555,
      userType: 'USER',
      longitude: 18.7322,
      latitude: 15.4542,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5640',
      name: 'Emily Scott',
      email: 'emily.scott@example.com',
      password: 'password54',
      country: 'Chile',
      hotels: [],
      phone: 6665554444,
      userType: 'ADMIN',
      longitude: -71.5429,
      latitude: -35.6751,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5641',
      name: 'James Mitchell',
      email: 'james.mitchell@example.com',
      password: 'password55',
      country: 'China',
      hotels: [],
      phone: 5554443333,
      userType: 'USER',
      longitude: 104.1954,
      latitude: 35.8617,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5642',
      name: 'Abigail Perez',
      email: 'abigail.perez@example.com',
      password: 'password56',
      country: 'Colombia',
      hotels: [],
      phone: 4443332222,
      userType: 'ADMIN',
      longitude: -74.2973,
      latitude: 4.5709,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5643',
      name: 'Noah Howard',
      email: 'noah.howard@example.com',
      password: 'password57',
      country: 'Comoros',
      hotels: [],
      phone: 3332221111,
      userType: 'USER',
      longitude: 43.8722,
      latitude: -11.875,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5644',
      name: 'Charlotte King',
      email: 'charlotte.king@example.com',
      password: 'password58',
      country: 'Congo (Congo-Brazzaville)',
      hotels: [],
      phone: 2223334444,
      userType: 'ADMIN',
      longitude: 15.8277,
      latitude: -0.228,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5645',
      name: 'Logan Wright',
      email: 'logan.wright@example.com',
      password: 'password59',
      country: 'Costa Rica',
      hotels: [],
      phone: 1112223333,
      userType: 'USER',
      longitude: -84.0916,
      latitude: 9.7489,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5646',
      name: 'Ella Martin',
      email: 'ella.martin@example.com',
      password: 'password60',
      country: 'Croatia',
      hotels: [],
      phone: 9998887777,
      userType: 'ADMIN',
      longitude: 15.2000,
      latitude: 45.1000,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5647',
      name: 'David Hughes',
      email: 'david.hughes@example.com',
      password: 'password61',
      country: 'Cuba',
      hotels: [],
      phone: 8889990000,
      userType: 'USER',
      longitude: -77.7812,
      latitude: 21.5218,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5648',
      name: 'Sophia Diaz',
      email: 'sophia.diaz@example.com',
      password: 'password62',
      country: 'Cyprus',
      hotels: [],
      phone: 7776665555,
      userType: 'ADMIN',
      longitude: 33.4299,
      latitude: 35.1264,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5649',
      name: 'William Bell',
      email: 'william.bell@example.com',
      password: 'password63',
      country: 'Czechia (Czech Republic)',
      hotels: [],
      phone: 6665554444,
      userType: 'USER',
      longitude: 15.473,
      latitude: 49.8175,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5650',
      name: 'Isabella Powell',
      email: 'isabella.powell@example.com',
      password: 'password64',
      country: 'Democratic Republic of the Congo',
      hotels: [],
      phone: 5554443333,
      userType: 'ADMIN',
      longitude: 15.8277,
      latitude: -0.228,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5651',
      name: 'Lucas Hughes',
      email: 'lucas.hughes@example.com',
      password: 'password65',
      country: 'Denmark',
      hotels: [],
      phone: 4443332222,
      userType: 'USER',
      longitude: 9.5018,
      latitude: 56.2639,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5652',
      name: 'Amelia Coleman',
      email: 'amelia.coleman@example.com',
      password: 'password66',
      country: 'Djibouti',
      hotels: [],
      phone: 3332221111,
      userType: 'ADMIN',
      longitude: 42.5903,
      latitude: 11.8251,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5653',
      name: 'Henry Coleman',
      email: 'henry.coleman@example.com',
      password: 'password67',
      country: 'Dominica',
      hotels: [],
      phone: 2223334444,
      userType: 'USER',
      longitude: -61.371,
      latitude: 15.4145,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5654',
      name: 'Harper Butler',
      email: 'harper.butler@example.com',
      password: 'password68',
      country: 'Dominican Republic',
      hotels: [],
      phone: 1112223333,
      userType: 'ADMIN',
      longitude: -70.1627,
      latitude: 18.7357,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5655',
      name: 'Jacob Kelly',
      email: 'jacob.kelly@example.com',
      password: 'password69',
      country: 'Ecuador',
      hotels: [],
      phone: 9998887777,
      userType: 'USER',
      longitude: -78.1834,
      latitude: -1.8312,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      imageId: '6151ee38c5b92b601f3d5656',
      name: 'Ella Nelson',
      email: 'ella.nelson@example.com',
      password: 'password70',
      country: 'Egypt',
      hotels: [],
      phone: 8889990000,
      userType: 'ADMIN',
      longitude: 30.8025,
      latitude: 26.8206,
      createdAt: new Date(),
      updatedAt: new Date()
    }
  ];
  
  const restaurants = [
    {
      restaurantName: "Italian Delights",
      city: "Rome",
      country: "Italy",
      deliveryPrice: 200,
      estimatedDeliveryTime: 30,
      cuisines: ["Italian"],
      menuItems: [
        { name: "Pizza Margherita", price: 8.99 },
        { name: "Caprese Salad", price: 7.99 }
      ],
      lastUpdated: new Date()
    },
    {
      restaurantName: "Taco Express",
      city: "Mexico City",
      country: "Mexico",
      deliveryPrice: 250,
      estimatedDeliveryTime: 25,
      cuisines: ["Mexican"],
      menuItems: [
        { name: "Chicken Tacos", price: 10.49 },
        { name: "Guacamole", price: 5.99 }
      ],
      lastUpdated: new Date()
    },
    {
      restaurantName: "Sushi Sensation",
      city: "Tokyo",
      country: "Japan",
      deliveryPrice: 180,
      estimatedDeliveryTime: 35,
      cuisines: ["Japanese"],
      menuItems: [
        { name: "Sashimi Platter", price: 15.99 },
        { name: "California Roll", price: 12.99 }
      ],
      lastUpdated: new Date()
    },
    {
      restaurantName: "French Bistro",
      city: "Paris",
      country: "France",
      deliveryPrice: 220,
      estimatedDeliveryTime: 30,
      cuisines: ["French"],
      menuItems: [
        { name: "Croque Monsieur", price: 9.99 },
        { name: "Escargot", price: 14.99 }
      ],
      lastUpdated: new Date()
    },
    {
      restaurantName: "Burger Haven",
      city: "New York City",
      country: "United States",
      deliveryPrice: 180,
      estimatedDeliveryTime: 20,
      cuisines: ["American"],
      menuItems: [
        { name: "Cheeseburger", price: 9.49 },
        { name: "Chicken Wings", price: 12.99 }
      ],
      lastUpdated: new Date()
    },
    {
      restaurantName: "Paella Palace",
      city: "Madrid",
      country: "Spain",
      deliveryPrice: 210,
      estimatedDeliveryTime: 35,
      cuisines: ["Spanish"],
      menuItems: [
        { name: "Seafood Paella", price: 17.99 },
        { name: "Tapas Selection", price: 13.99 }
      ],
      lastUpdated: new Date()
    },
    {
      restaurantName: "Indian Spices",
      city: "Mumbai",
      country: "India",
      deliveryPrice: 190,
      estimatedDeliveryTime: 30,
      cuisines: ["Indian"],
      menuItems: [
        { name: "Butter Chicken", price: 11.99 },
        { name: "Vegetable Biryani", price: 9.99 }
      ],
      lastUpdated: new Date()
    },
    {
      restaurantName: "Greek Taverna",
      city: "Athens",
      country: "Greece",
      deliveryPrice: 200,
      estimatedDeliveryTime: 25,
      cuisines: ["Greek"],
      menuItems: [
        { name: "Moussaka", price: 14.99 },
        { name: "Souvlaki", price: 8.99 }
      ],
      lastUpdated: new Date()
    },
    {
      restaurantName: "Thai Spice",
      city: "Bangkok",
      country: "Thailand",
      deliveryPrice: 230,
      estimatedDeliveryTime: 30,
      cuisines: ["Thai"],
      menuItems: [
        { name: "Pad Thai", price: 9.99 },
        { name: "Green Curry", price: 11.99 }
      ],
      lastUpdated: new Date()
    },
    {
      restaurantName: "Brazilian BBQ",
      city: "Rio de Janeiro",
      country: "Brazil",
      deliveryPrice: 240,
      estimatedDeliveryTime: 35,
      cuisines: ["Brazilian"],
      menuItems: [
        { name: "Churrasco", price: 19.99 },
        { name: "Feijoada", price: 16.99 }
      ],
      lastUpdated: new Date()
    },
    {
      restaurantName: "Vietnamese Pho",
      city: "Hanoi",
      country: "Vietnam",
      deliveryPrice: 210,
      estimatedDeliveryTime: 30,
      cuisines: ["Vietnamese"],
      menuItems: [
        { name: "Beef Pho", price: 8.99 },
        { name: "Spring Rolls", price: 6.99 }
      ],
      lastUpdated: new Date()
    },
    {
      restaurantName: "Peruvian Delights",
      city: "Lima",
      country: "Peru",
      deliveryPrice: 220,
      estimatedDeliveryTime: 25,
      cuisines: ["Peruvian"],
      menuItems: [
        { name: "Ceviche", price: 15.99 },
        { name: "Lomo Saltado", price: 17.99 }
      ],
      lastUpdated: new Date()
    },
    {
      restaurantName: "Korean BBQ House",
      city: "Seoul",
      country: "South Korea",
      deliveryPrice: 200,
      estimatedDeliveryTime: 30,
      cuisines: ["Korean"],
      menuItems: [
        { name: "Bulgogi", price: 18.99 },
        { name: "Kimchi", price: 5.99 }
      ],
      lastUpdated: new Date()
    },
    {
      restaurantName: "Swiss Fondue",
      city: "Zurich",
      country: "Switzerland",
      deliveryPrice: 250,
      estimatedDeliveryTime: 40,
      cuisines: ["Swiss"],
      menuItems: [
        { name: "Cheese Fondue", price: 22.99 },
        { name: "Rösti", price: 12.99 }
      ],
      lastUpdated: new Date()
    },
    {
      restaurantName: "Moroccan Feast",
      city: "Marrakesh",
      country: "Morocco",
      deliveryPrice: 230,
      estimatedDeliveryTime: 35,
      cuisines: ["Moroccan"],
      menuItems: [
        { name: "Tagine", price: 16.99 },
        { name: "Couscous", price: 14.99 }
      ],
      lastUpdated: new Date()
    },
    {
      restaurantName: "Australian Outback",
      city: "Sydney",
      country: "Australia",
      deliveryPrice: 240,
      estimatedDeliveryTime: 30,
      cuisines: ["Australian"],
      menuItems: [
        { name: "BBQ Shrimp", price: 20.99 },
        { name: "Meat Pie", price: 8.99 }
      ],
      lastUpdated: new Date()
    },
    {
      restaurantName: "Dutch Pancakes",
      city: "Amsterdam",
      country: "Netherlands",
      deliveryPrice: 210,
      estimatedDeliveryTime: 25,
      cuisines: ["Dutch"],
      menuItems: [
        { name: "Poffertjes", price: 9.99 },
        { name: "Stroopwafel", price: 6.99 }
      ],
      lastUpdated: new Date()
    },
    {
      restaurantName: "Turkish Delights",
      city: "Istanbul",
      country: "Turkey",
      deliveryPrice: 220,
      estimatedDeliveryTime: 30,
      cuisines: ["Turkish"],
      menuItems: [
        { name: "Kebab", price: 12.99 },
        { name: "Baklava", price: 7.99 }
      ],
      lastUpdated: new Date()
    },
    {
      restaurantName: "South African Braai",
      city: "Cape Town",
      country: "South Africa",
      deliveryPrice: 230,
      estimatedDeliveryTime: 35,
      cuisines: ["South African"],
      menuItems: [
        { name: "Boerewors", price: 14.99 },
        { name: "Biltong", price: 18.99 }
      ],
      lastUpdated: new Date()
    },
  ];  
  // Function to convert country names to abbreviations
  function convertCountryToAbbreviation(countryName) {
    return countryMappings[countryName] || countryName; // Return abbreviation or original name if not found
  }
  const restaurantsWithAbbreviations = restaurants.map(restaurant => ({
    ...restaurant,
    country: convertCountryToAbbreviation(restaurant.country)
  }));
  // Iterate through users array and convert country names to abbreviations
  const usersWithAbbreviations = users.map(user => ({
    ...user,
    country: convertCountryToAbbreviation(user.country)
  }));
    
  export {orders, bookings, usersWithAbbreviations, restaurantsWithAbbreviations};